from PyQt5 import QtCore, QtGui, QtWidgets


class addGame_Ui_Dialog(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
    def addGame_setupUi(self, Dialog):
        self.gamedialog = Dialog
        self.gamedialog.setObjectName("Dialog")
        self.gamedialog.resize(808, 880)
        self.gamedialog.setStyleSheet("background-color: rgb(85, 85, 127);")

        self.label = QtWidgets.QLabel(self.gamedialog)
        self.label.setGeometry(QtCore.QRect(90, 270, 251, 251))
        self.label.setStyleSheet("background-image: url(:/newPrefix/User.png);")
        self.label.setText("")
        self.label.setObjectName("label")

        self.frame = QtWidgets.QFrame(self.gamedialog)
        self.frame.setGeometry(QtCore.QRect(100, 50, 611, 751))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(160, 40, 331, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(32)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_2.setObjectName("label_2")

        self.label_1 = QtWidgets.QLabel(self.frame)
        self.label_1.setGeometry(QtCore.QRect(170, 120, 331, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: rgb(244, 35, 20);")
        self.label_1.setObjectName("label_1")

        self.gameName = QtWidgets.QLabel(self.frame)
        self.gameName.setGeometry(QtCore.QRect(40, 190, 331, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.gameName.setFont(font)
        self.gameName.setStyleSheet("color: rgb(0, 0, 0);")
        self.gameName.setObjectName("gameName")

        self.gameNameField = QtWidgets.QLineEdit(self.frame)
        self.gameNameField.setGeometry(QtCore.QRect(260, 200, 331, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.gameNameField.setFont(font)
        self.gameNameField.setStyleSheet("color: rgb(244, 35, 20);")
        self.gameNameField.setObjectName("gameNameField")

        self.gamePubliser = QtWidgets.QLabel(self.frame)
        self.gamePubliser.setGeometry(QtCore.QRect(40, 250, 331, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.gamePubliser.setFont(font)
        self.gamePubliser.setStyleSheet("color: rgb(0, 0, 0);")
        self.gamePubliser.setObjectName("gamePubliser")

        self.artistNameField = QtWidgets.QLineEdit(self.frame)
        self.artistNameField.setGeometry(QtCore.QRect(260, 260, 331, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.artistNameField.setFont(font)
        self.artistNameField.setStyleSheet("color: rgb(244, 35, 20);")
        self.artistNameField.setObjectName("artistNameField")

        self.gameYear = QtWidgets.QLabel(self.frame)
        self.gameYear.setGeometry(QtCore.QRect(40, 310, 331, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.gameYear.setFont(font)
        self.gameYear.setStyleSheet("color: rgb(0, 0, 0);")
        self.gameYear.setObjectName("gameYear")

        self.yearField = QtWidgets.QLineEdit(self.frame)
        self.yearField.setGeometry(QtCore.QRect(260, 320, 331, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.yearField.setFont(font)
        self.yearField.setStyleSheet("color: rgb(244, 35, 20);")
        self.yearField.setObjectName("yearField")

        self.gamePlatform = QtWidgets.QLabel(self.frame)
        self.gamePlatform.setGeometry(QtCore.QRect(40, 370, 331, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.gamePlatform.setFont(font)
        self.gamePlatform.setStyleSheet("color: rgb(0, 0, 0);")
        self.gamePlatform.setObjectName("gamePlatform")

        self.writerField = QtWidgets.QLineEdit(self.frame)
        self.writerField.setGeometry(QtCore.QRect(260, 380, 331, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.writerField.setFont(font)
        self.writerField.setStyleSheet("color: rgb(244, 35, 20);")
        self.writerField.setObjectName("writerField")

        self.genreName = QtWidgets.QLabel(self.frame)
        self.genreName.setGeometry(QtCore.QRect(40, 430, 331, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.genreName.setFont(font)
        self.genreName.setStyleSheet("color: rgb(0, 0, 0);")
        self.genreName.setObjectName("genreName")

        self.genreField = QtWidgets.QLineEdit(self.frame)
        self.genreField.setGeometry(QtCore.QRect(260, 440, 331, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.genreField.setFont(font)
        self.genreField.setStyleSheet("color: rgb(244, 35, 20);")
        self.genreField.setObjectName("genreField")

        self.fileUploadField = QtWidgets.QLineEdit(self.frame)
        self.fileUploadField.setGeometry(QtCore.QRect(20, 500, 451, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.fileUploadField.setFont(font)
        self.fileUploadField.setStyleSheet("color: rgb(0, 0, 0);")
        self.fileUploadField.setObjectName("fileUploadField")

        self.searchFile = QtWidgets.QPushButton(self.frame)
        self.searchFile.setGeometry(QtCore.QRect(450, 500, 140, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.searchFile.setFont(font)
        self.searchFile.setStyleSheet("background-color: rgb(25, 25, 112);\n"
                                        "color: rgb(255, 255, 255);")
        self.searchFile.clicked.connect(self.dialog)
        self.searchFile.setObjectName("searchFile")

        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 600, 260, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(244, 35, 20);\n"
                                      "color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton")

        self.AddButton = QtWidgets.QPushButton(self.frame)
        self.AddButton.setGeometry(QtCore.QRect(20, 600, 260, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddButton.setFont(font)
        self.AddButton.setStyleSheet("background-color: rgb(244, 35, 20);\n"
                                        "color: rgb(255, 255, 255);")
        self.AddButton.setObjectName("AddButton")
        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setGeometry(QtCore.QRect(180, 660, 260, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgb(244, 35, 20);\n"
                                      "color: rgb(255, 255, 255);")
        self.backButton.setObjectName("backButton")
        self.retranslateUi(self.gamedialog)
        QtCore.QMetaObject.connectSlotsByName(self.gamedialog)
        return self.gamedialog

    def dialog(self):
        file, check = QtWidgets.QFileDialog.getOpenFileName(None, "QFileDialog.getOpenFileName()",
                                                  "", "All Files (*);;Python Files (*.py);;Text Files (*.txt)")
        if check:
            self.fileUploadField.setText(file)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select Category"))
        self.label_2.setText(_translate("Dialog", "Media Library"))
        self.label_1.setText(_translate("Dialog", "Add Game File"))
        self.gameName.setText(_translate("Dialog", "Game Name"))
        self.gamePubliser.setText(_translate("Dialog", "Game Publisher"))
        self.gameYear.setText(_translate("Dialog", "Game Year"))
        self.gamePlatform.setText(_translate("Dialog", "Game Platform"))
        self.genreName.setText(_translate("Dialog", "Genre Name"))
        self.searchFile.setText(_translate("Dialog", "Search"))
        self.AddButton.setText(_translate("Dialog", "Upload"))
        self.pushButton_3.setText(_translate("Dialog", "Logout"))
        self.backButton.setText(_translate("Dialog", "Back"))

